### ISSUE TITLE
RPC methods meta issue

### ISSUE THREAD

**Issue by svyatonik** [paritytech/parity-zcash#27]
- [x] `BlockChain`:
- - [x] `getbestblockhash`;
- - [x] `getblockcount`;
- - [x] `getblockhash`;
- - [x] `getdifficulty` - currently returns difficulty of the best block. Should calculate difficulty for next block. TODO: check `pbtc`;
- - [x] `getblock` - update response with ZCash-specific fields;
- - [x] `gettxout` - check if we need non-transparent addresses for this;
- - [x] `gettxoutsetinfo` - not implemented in `pbtc`.
- [ ] `Miner`:
- - [ ] `getblocktemplate` - update with ZCash-specific fields (`finalsaplingroot`).
- [x] `Network`:
- - [x] `addnode`;
- - [x] `getaddednodeinfo`;
- - [x] `getconnectioncount`.
- [x] `Raw`:
- - [x] `sendrawtransaction`;
- - [x] `createrawtransaction` - update with ZCash-specific fields + addresses;
- - [x] `decoderawtransaction` - not implemented in `pbtc`.
- - [x] `getrawtransaction` - not implemented in `pbtc`.

**Comment by svyatonik** [comment]
This is currently blocked by the fact that currently `jsonrpc_macro` doesn't support more than one optional `Trailing` argument && we need more in some RPC methods (`createrawtransaction` is the first example). So we need either to support this case in `jsonrpc` (preferable) or to do a custom args parsing in `pzec`.

I was researching if that's easy-to-add-feature to the existing `jsonrpc_macro` && looks like it is, but the problem is that it would require custom macro of ~150 LOCs for every number of trailing args that we're going to support (i.e. if there'll be RPC with 6 optional trailing args, we'll need ~1KLOC), which isn't ideal. Moreover, today I stumbled upon [this PR](https://github.com/paritytech/jsonrpc/pull/340), which should obsolete `jsonrpc_macro`. So I'm currently researching if this is easy/possible to support multiple optional args in `jsonrpc-derive`. If so, then we'll probably switch to custom `jsonrpc` branch until new version is merged && published.

**Comment by ascjones** [comment]
Yes should be able to support multiple optional args with jsonrpc-derive, see [here](https://github.com/paritytech/jsonrpc/blob/04700f9f4f3d0ff5b0b314a9796c868cb5cff56f/derive/src/to_delegate.rs#L296). Just need to fill in the missing ones with `None`.

**Comment by ascjones** [comment]
@svyatonik  `jsonrpc-derive` is now merged, I've added an issue https://github.com/paritytech/jsonrpc/issues/363 to implement multiple trailing params. I'm happy to do the work to rebase your branch - just let me know.

By the way the issue with failing to deserialize single tuple was because of a missing comma. Single param tuple should be `(u64,)`.

**Comment by svyatonik** [comment]
Thanks! I'll open PR a bit later && will cc you :)
